misc: modify ci-tests workflow to run gcovr and upload to Codecov
This commit modifies the ci-tests workflow to run gcovr on the
unittests and the TestLib tests and upload the coverage xml files
to Codecov.

For testing purposes, this file only runs the riscv-boot-tests,
and also uses GitHub's runners instead of Loupe

diff --git a/.github/workflows/ci-tests.yaml b/.github/workflows/ci-tests.yaml
--- a/.github/workflows/ci-tests.yaml
+++ b/.github/workflows/ci-tests.yaml
@@ -1,11 +1,11 @@
 ---
 # This workflow runs after a pull-request has been approved by a reviewer.
 
-name: CI Tests
+name: CI Tests with gcovr code coverage metrics
 
-on:
-    pull_request:
-        types: [opened, synchronize, ready_for_review]
+on: workflow_dispatch
+    # pull_request:
+    #     types: [opened, synchronize, ready_for_review]
 
 concurrency:
     group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
@@ -78,7 +78,8 @@ jobs:
         strategy:
             matrix:
                 type: [fast, opt]
-        runs-on: [self-hosted, linux, x64]
+        #runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         if: github.event.pull_request.draft == false
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         needs: [pre-commit] # only runs if pre-commit passes.
@@ -87,7 +88,17 @@ jobs:
             - uses: actions/checkout@v4
             - name: CI Unittests (${{ matrix.type }})
               working-directory: ${{ github.workspace }}
-              run: scons --no-compress-debug build/ALL/unittests.${{ matrix.type }} -j $(nproc)
+              run: scons --no-compress-debug build/ALL/unittests.${{ matrix.type }} --gcov -j $(nproc)
+            - name: Run gcovr
+              working-directory: ${{ github.workspace }}
+              run: gcovr --verbose --merge-mode-functions separate --gcov-ignore-parse-errors=suspicious_hits.warn --gcov-ignore-parse-errors=negative_hits.warn
+                  --root ${{ github.workspace }} --object-directory ${{ github.workspace }}/build/ALL --xml unittests.xml
+
+            - name: Upload coverage reports to Codecov
+              uses: codecov/codecov-action@v5
+              with:
+                  token: ${{ secrets.CODECOV_TOKEN }}
+                  files: ./unittests.xml
             - run: echo "This job's status is ${{ job.status }}."
 
     testlib-quick-matrix:
@@ -99,95 +110,100 @@ jobs:
         needs: [pre-commit]
         steps:
             - uses: actions/checkout@v4
+            # modify this step to only return riscv_boot_tests, for testing purposes
             - name: Get directories for testlib-quick
               working-directory: ${{ github.workspace }}/tests
               id: dir-matrix
               run: |
                   unset PREV
-                  echo "test-dirs-matrix=$(\
-                    ./main.py list gem5 \
-                    --suites \
-                    --exclude-tags gcn_gpu | \
-                    grep "$SUITEUID:" | \
-                    cut -d: -f2 | \
-                    cut -d/ -f 2- | \
-                    xargs dirname | \
-                    sort -u  | \
-                    while read x; do \
-                      if [ -z "${PREV}" ] || [ "$x" != "${PREV}/*" ]; then \
-                        PREV=$x; \
-                        echo $x; \
-                      fi; \
-                    done  | \
-                    jq -ncR '[inputs]'\
-                  )" >>$GITHUB_OUTPUT
+                  echo 'test-dirs-matrix=["gem5/riscv_boot_tests"]' >>$GITHUB_OUTPUT
+
+                #   echo "test-dirs-matrix=$(\
+                #     ./main.py list gem5 \
+                #     --suites \
+                #     --exclude-tags gcn_gpu | \
+                #     grep "$SUITEUID:" | \
+                #     cut -d: -f2 | \
+                #     cut -d/ -f 2- | \
+                #     xargs dirname | \
+                #     sort -u  | \
+                #     while read x; do \
+                #       if [ -z "${PREV}" ] || [ "$x" != "${PREV}/*" ]; then \
+                #         PREV=$x; \
+                #         echo $x; \
+                #       fi; \
+                #     done  | \
+                #     jq -ncR '[inputs]'\
+                #   )" >>$GITHUB_OUTPUT
 
             - name: Get the build targets for testlib-quick-gem5-builds
               working-directory: ${{ github.workspace }}/tests
               id: build-matrix
-              run: echo "build-matrix=$(./main.py list --build-targets --exclude-tags VEGA_X86 -q | jq -ncR '[inputs]')" >>$GITHUB_OUTPUT
+              run: echo "build-matrix=$(./main.py list --build-targets --gcov --exclude-tags VEGA_X86 -q | jq -ncR '[inputs]')" >>$GITHUB_OUTPUT
 
         outputs:
             build-matrix: ${{ steps.build-matrix.outputs.build-matrix }}
             test-dirs-matrix: ${{ steps.dir-matrix.outputs.test-dirs-matrix }}
 
-    clang-fast-compilation:
-        # gem5 binaries built in `quick-gem5-builds` always use GCC.
-        # Clang is more strict than GCC. This job checks that gem5 compiles
-        # with Clang. It compiles build/ALL/gem5.fast to maximize the change
-        # for compilation error to be exposed.
-        runs-on: [self-hosted, linux, x64]
-        if: github.event.pull_request.draft == false
-        container: ghcr.io/gem5/clang-version-19:latest
-        needs: [pre-commit]
-        timeout-minutes: 90
-        steps:
-            - uses: actions/checkout@v4
-            - name: Clang Compilation
-              working-directory: ${{ github.workspace }}
-              run: scons build/ALL/gem5.fast -j $(nproc)
+    # clang-fast-compilation:
+    #     # gem5 binaries built in `quick-gem5-builds` always use GCC.
+    #     # Clang is more strict than GCC. This job checks that gem5 compiles
+    #     # with Clang. It compiles build/ALL/gem5.fast to maximize the change
+    #     # for compilation error to be exposed.
+    #     #runs-on: [self-hosted, linux, x64]
+          # runs-on: ubuntu-24.04
+    #     if: github.event.pull_request.draft == false
+    #     container: ghcr.io/gem5/clang-version-19:latest
+    #     needs: [pre-commit]
+    #     timeout-minutes: 90
+    #     steps:
+    #         - uses: actions/checkout@v4
+    #         - name: Clang Compilation
+    #           working-directory: ${{ github.workspace }}
+    #           run: scons build/ALL/gem5.fast -j $(nproc)
 
-    macos-compilation:
-        runs-on: macos-26
-        if: github.event.pull_request.draft == false
-        needs: [pre-commit, get-date]
+    # macos-compilation:
+    #     runs-on: macos-26
+    #     if: github.event.pull_request.draft == false
+    #     needs: [pre-commit, get-date]
 
-        strategy:
-            fail-fast: false
-            matrix:
-                type: [fast, opt]
+    #     strategy:
+    #         fail-fast: false
+    #         matrix:
+    #             type: [fast, opt]
 
-        steps:
-            - name: Checkout the gem5 repository
-              uses: actions/checkout@v4
+    #     steps:
+    #         - name: Checkout the gem5 repository
+    #           uses: actions/checkout@v4
 
-            - name: Install the gem5 dependencies
-              run: |
-                  brew update
-                  brew install \
-                    scons \
-                    python \
-                    pkg-config \
-                    protobuf \
-                    grpc \
-                    boost
+    #         - name: Install the gem5 dependencies
+    #           run: |
+    #               brew update
+    #               brew install \
+    #                 scons \
+    #                 python \
+    #                 pkg-config \
+    #                 protobuf \
+    #                 grpc \
+    #                 boost
 
 
-            - name: Restore macOS build/ALL cache
-              uses: actions/cache/restore@v4
-              with:
-                  path: build/ALL
-                  key: macos-all-gem5-${{ matrix.type }}-${{ needs.get-date.outputs.date }}
-                  restore-keys: |
-                      macos-all-gem5-${{ matrix.type }}
+    #         - name: Restore macOS build/ALL cache
+    #           uses: actions/cache/restore@v4
+    #           with:
+    #               path: build/ALL
+    #               key: macos-all-gem5-${{ matrix.type }}-${{ needs.get-date.outputs.date }}
+    #               restore-keys: |
+    #                   macos-all-gem5-${{ matrix.type }}
 
-            - name: Compile gem5.${{ matrix.type }}
-              working-directory: ${{ github.workspace }}
-              run: scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)
-              timeout-minutes: 90
+    #         - name: Compile gem5.${{ matrix.type }}
+    #           working-directory: ${{ github.workspace }}
+    #           run: scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)
+    #           timeout-minutes: 90
 
     testlib-quick-gem5-builds:
-        runs-on: [self-hosted, linux, x64]
+        #runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         if: github.event.pull_request.draft == false
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         needs: [pre-commit, testlib-quick-matrix, get-date]
@@ -199,7 +215,7 @@ jobs:
 
             - name: Cache build/ALL
               uses: actions/cache/restore@v4
-              if: ${{ endsWith(matrix.build-target, 'build/ALL/gem5.opt') }}
+              if: ${{ endsWith(matrix.build-target, 'build/ALL/gem5.debug') }}
               with:
                   path: build/ALL
                   key: testlib-build-all-${{ needs.get-date.outputs.date }}
@@ -232,7 +248,8 @@ jobs:
 
     testlib-quick-execution:
         name: quick-tests
-        runs-on: [self-hosted, linux, x64]
+        # runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         if: github.event.pull_request.draft == false
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         needs: [pre-commit, testlib-quick-matrix, testlib-quick-gem5-builds]
@@ -261,13 +278,19 @@ jobs:
             - name: Run quick ${{ matrix.test-dir }} tests
               id: run-tests
               working-directory: ${{ github.workspace }}/tests
-              run: ./main.py run --skip-build --exclude-tags gcn_gpu ${{  matrix.test-dir }}
+              run: ./main.py run --skip-build --exclude-tags gcn_gpu --gcov=all-test-and-gcov ${{  matrix.test-dir }}
 
         # Get the basename of the matrix.test-dir path (to name the artifact).
             - name: Sanitize test-dir for artifact name
               id: sanitize-test-dir
               if: success() || failure()
               run: echo "sanitized-test-dir=$(echo '${{ matrix.test-dir }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT
+
+            - name: Upload coverage reports to Codecov
+              uses: codecov/codecov-action@v5
+              with:
+                  token: ${{ secrets.CODECOV_TOKEN }}\
+                  files: ./build/ALL/ALL-gcov-results.xml
 
         # Upload the tests/testing-results directory as an artifact.
             - name: Upload results
@@ -279,36 +302,42 @@ jobs:
                   path: tests/testing-results
                   retention-days: 30
 
-    gpu-tests:
-        runs-on: [self-hosted, linux, x64]
-        container: ghcr.io/gem5/gcn-gpu:latest
-        timeout-minutes: 180
-        needs: [pre-commit, get-date]
-        steps:
-            - uses: actions/checkout@v4
+    # gpu-tests:
+    #     #runs-on: [self-hosted, linux, x64]
+# runs-on: ubuntu-24.04
+    #     container: ghcr.io/gem5/gcn-gpu:latest
+    #     timeout-minutes: 180
+    #     needs: [pre-commit, get-date]
+    #     steps:
+    #         - uses: actions/checkout@v4
 
-            # Obtain the cache if available.
-            - name: Cache build/VEGA_X86
-              uses: actions/cache/restore@v4
-              with:
-                  path: build/VEGA_X86
-                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
-                  restore-keys: |
-                      testlib-build-vega
+    #         # Obtain the cache if available.
+    #         - name: Cache build/VEGA_X86
+    #           uses: actions/cache/restore@v4
+    #           with:
+    #               path: build/VEGA_X86
+    #               key: testlib-build-vega-${{ needs.get-date.outputs.date }}
+    #               restore-keys: |
+    #                   testlib-build-vega
 
-            # Run the GPU tests.
-            - name: Run Testlib GPU Tests
-              id: run-tests
-              working-directory: ${{ github.workspace }}/tests
-              run: ./main.py run -j$(nproc) -t$(nproc) --host gcn_gpu
+    #         # Run the GPU tests.
+    #         - name: Run Testlib GPU Tests
+    #           id: run-tests
+    #           working-directory: ${{ github.workspace }}/tests
+    #           run: ./main.py run --gcov=all-test-and-gcov -j$(nproc) -t$(nproc) --host gcn_gpu
 
-            # Upload the tests/testing-results directory as an artifact.
-            - name: Upload results
-              if: success() || failure()
-              uses: actions/upload-artifact@v4
-              with:
-                  name: ci-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gpu-status-${{ steps.run-tests.outcome }}-output
-                  path: tests/testing-results
+    #         - name: Upload coverage reports to Codecov
+    #           uses: codecov/codecov-action@v5
+    #           with:
+    #             token: ${{ secrets.CODECOV_TOKEN }}
+
+    #         # Upload the tests/testing-results directory as an artifact.
+    #         - name: Upload results
+    #           if: success() || failure()
+    #           uses: actions/upload-artifact@v4
+    #           with:
+    #               name: ci-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gpu-status-${{ steps.run-tests.outcome }}-output
+    #               path: tests/testing-results
 
     ci-tests:
     # It is 'testlib-quick' which needs to pass for the pull request to be
@@ -320,6 +349,6 @@ jobs:
             - unittests-all-fast-opt
             - macos-compilation
             - pre-commit
-            - gpu-tests
+            # - gpu-tests
         steps:
             - run: echo "This job's status is ${{ job.status }}."
