misc: modify daily tests workflow, arm boot tests for testing
This commit modifies the daily tests to only run the arm and x86
boot tests, modifies them to actually run the quick tests, and
modifies the arm tests so the match regex should fail.

diff --git a/.github/workflows/daily-tests.yml b/.github/workflows/daily-tests.yml
--- a/.github/workflows/daily-tests.yml
+++ b/.github/workflows/daily-tests.yml
@@ -20,63 +20,63 @@ jobs:
               id: date
               run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
 
-    macos-compilation:
-        # The purpose of this is to cache the macOS compilation.
-        # MacOS compilation checks are run as part of the CI tests but as the
-        # MacOS GitHub action runners are quite costly, it's advantageous to
-        # build upon a cache. Putting this in the daily tests means that the
-        # cache is refreshed on a daily basis.
-        runs-on: macos-26
-        needs: get-date
+    # macos-compilation:
+    #     # The purpose of this is to cache the macOS compilation.
+    #     # MacOS compilation checks are run as part of the CI tests but as the
+    #     # MacOS GitHub action runners are quite costly, it's advantageous to
+    #     # build upon a cache. Putting this in the daily tests means that the
+    #     # cache is refreshed on a daily basis.
+    #     runs-on: macos-26
+    #     needs: get-date
 
-        strategy:
-            fail-fast: false
-            matrix:
-                type: [fast, opt]
+    #     strategy:
+    #         fail-fast: false
+    #         matrix:
+    #             type: [fast, opt]
 
-        steps:
-            - name: Checkout the gem5 repository
-              uses: actions/checkout@v4
+    #     steps:
+    #         - name: Checkout the gem5 repository
+    #           uses: actions/checkout@v4
 
-            - name: Install the gem5 dependencies
-              run: |
-                  brew update
-                  brew install \
-                    scons \
-                    python \
-                    pkg-config \
-                    protobuf \
-                    grpc \
-                    boost
+    #         - name: Install the gem5 dependencies
+    #           run: |
+    #               brew update
+    #               brew install \
+    #                 scons \
+    #                 python \
+    #                 pkg-config \
+    #                 protobuf \
+    #                 grpc \
+    #                 boost
 
 
-            - name: Cache macOS build/ALL
-              uses: actions/cache@v4
-              with:
-                  path: build/ALL
-                  key: macos-all-gem5-${{ matrix.type }}-${{ needs.get-date.outputs.date }}
-                  restore-keys: |
-                      macos-all-gem5-${{ matrix.type }}
+    #         - name: Cache macOS build/ALL
+    #           uses: actions/cache@v4
+    #           with:
+    #               path: build/ALL
+    #               key: macos-all-gem5-${{ matrix.type }}-${{ needs.get-date.outputs.date }}
+    #               restore-keys: |
+    #                   macos-all-gem5-${{ matrix.type }}
 
-            - name: Compile gem5.${{ matrix.type }}
-              working-directory: ${{ github.workspace }}
-              run: |
-                  CMD="scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)"
-                  ${CMD}
-                  status=$?
-                  if [ $status -ne 0 ]; then
-                      echo "Failed to build on top of cached build." 1>&2
-                      echo "This may be due to env changes since the cache build." 1>&2
-                      echo "Clearing cache and attempting another build..." 1>&2
-                      rm -rf build
-                      ${CMD}
-                      status=$?
-                  fi
-                  exit $status
-              timeout-minutes: 120
+    #         - name: Compile gem5.${{ matrix.type }}
+    #           working-directory: ${{ github.workspace }}
+    #           run: |
+    #               CMD="scons build/ALL/gem5.${{ matrix.type }} -j $(sysctl -n hw.ncpu)"
+    #               ${CMD}
+    #               status=$?
+    #               if [ $status -ne 0 ]; then
+    #                   echo "Failed to build on top of cached build." 1>&2
+    #                   echo "This may be due to env changes since the cache build." 1>&2
+    #                   echo "Clearing cache and attempting another build..." 1>&2
+    #                   rm -rf build
+    #                   ${CMD}
+    #                   status=$?
+    #               fi
+    #               exit $status
+    #           timeout-minutes: 120
 
     build-all-gem5:
-        runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         timeout-minutes: 180
         needs: get-date
@@ -100,7 +100,7 @@ jobs:
         strategy:
             matrix:
                 type: [debug]
-        runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         timeout-minutes: 60
         steps:
@@ -121,29 +121,12 @@ jobs:
               id: dir-matrix
               run: |
                   unset PREV
-                  echo "test-dirs-matrix=$(\
-                    ./main.py list gem5 \
-                    --suites \
-                    --length=long \
-                    --exclude-tags gcn_gpu | \
-                    grep "$SUITEUID:" | \
-                    cut -d: -f2 | \
-                    cut -d/ -f 2- | \
-                    xargs dirname | \
-                    sort -u  | \
-                    while read x; do \
-                      if [ -z "${PREV}" ] || [ "$x" != "${PREV}/*" ]; then \
-                        PREV=$x; \
-                        echo $x; \
-                      fi; \
-                    done  | \
-                    jq -ncR '[inputs]'\
-                  )" >>$GITHUB_OUTPUT
+                  echo "test-dirs-matrix=["gem5/arm_boot_tests", "gem5/x86_boot_tests"]" >>$GITHUB_OUTPUT
 
   # start running all of the long tests
     testlib-long-tests:
         name: long-tests
-        runs-on: [self-hosted, linux, x64]
+        runs-on: ubuntu-24.04
         container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
         timeout-minutes: 1440 # 24 hours for entire matrix to run
         needs:
@@ -187,99 +170,99 @@ jobs:
                   path: tests/testing-results
 
 
-    gpu-tests:
-        runs-on: [self-hosted, linux, x64]
-        container: ghcr.io/gem5/gcn-gpu:latest
-        timeout-minutes: 1440 # 24 hours
-        needs:
-            - get-date
+    # gpu-tests:
+    #     runs-on: ubuntu-24.04
+    #     container: ghcr.io/gem5/gcn-gpu:latest
+    #     timeout-minutes: 1440 # 24 hours
+    #     needs:
+    #         - get-date
 
-        steps:
-            - uses: actions/checkout@v4
-            - name: Cache build/VEGA_X86
-              uses: actions/cache@v4
-              with:
-                  path: build/VEGA_X86
-                  key: testlib-build-vega-${{ needs.get-date.outputs.date }}
-                  restore-keys: |
-                      testlib-build-vega
+    #     steps:
+    #         - uses: actions/checkout@v4
+    #         - name: Cache build/VEGA_X86
+    #           uses: actions/cache@v4
+    #           with:
+    #               path: build/VEGA_X86
+    #               key: testlib-build-vega-${{ needs.get-date.outputs.date }}
+    #               restore-keys: |
+    #                   testlib-build-vega
 
 
-            - name: Run Testlib GPU Tests
-              id: run-tests
-              timeout-minutes: 1410
-              working-directory: ${{ github.workspace }}/tests
-              run: ./main.py run --length=long -vvv -j $(nproc) --host gcn_gpu
+    #         - name: Run Testlib GPU Tests
+    #           id: run-tests
+    #           timeout-minutes: 1410
+    #           working-directory: ${{ github.workspace }}/tests
+    #           run: ./main.py run --length=long -vvv -j $(nproc) --host gcn_gpu
 
-            - name: Upload results
-              if: always()
-              uses: actions/upload-artifact@v4
-              with:
-                  name: ci-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gpu-status-${{ steps.run-tests.outcome }}-output
-                  path: tests/testing-results
+    #         - name: Upload results
+    #           if: always()
+    #           uses: actions/upload-artifact@v4
+    #           with:
+    #               name: ci-tests-run-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gpu-status-${{ steps.run-tests.outcome }}-output
+    #               path: tests/testing-results
 
   # This runs the SST-gem5 integration compilation and tests it with
   # ext/sst/sst/example.py.
-    sst-test:
-        runs-on: [self-hosted, linux, x64]
-        container: ghcr.io/gem5/sst-env:latest
-        timeout-minutes: 180
+  #   sst-test:
+  #       runs-on: ubuntu-24.04
+  #       container: ghcr.io/gem5/sst-env:latest
+  #       timeout-minutes: 180
 
-        steps:
-            - uses: actions/checkout@v4
-            - name: Build RISCV/libgem5_opt.so with SST
-              run: scons build/RISCV/libgem5_opt.so --without-tcmalloc --duplicate-sources --ignore-style -j $(nproc)
-            - name: Makefile ext/sst
-              working-directory: ${{ github.workspace }}/ext/sst
-              run: mv Makefile.linux Makefile
-            - name: Compile ext/sst
-              working-directory: ${{ github.workspace }}/ext/sst
-              run: make -j $(nproc)
-            - name: Run SST test
-              working-directory: ${{ github.workspace }}/ext/sst
-              run: sst --add-lib-path=./ sst/example.py
+  #       steps:
+  #           - uses: actions/checkout@v4
+  #           - name: Build RISCV/libgem5_opt.so with SST
+  #             run: scons build/RISCV/libgem5_opt.so --without-tcmalloc --duplicate-sources --ignore-style -j $(nproc)
+  #           - name: Makefile ext/sst
+  #             working-directory: ${{ github.workspace }}/ext/sst
+  #             run: mv Makefile.linux Makefile
+  #           - name: Compile ext/sst
+  #             working-directory: ${{ github.workspace }}/ext/sst
+  #             run: make -j $(nproc)
+  #           - name: Run SST test
+  #             working-directory: ${{ github.workspace }}/ext/sst
+  #             run: sst --add-lib-path=./ sst/example.py
 
-  # This runs the gem5 within SystemC ingration and runs a simple hello-world
-  # simulation with it.
-    systemc-test:
-        runs-on: [self-hosted, linux, x64]
-        container: ghcr.io/gem5/systemc-env:latest
-        timeout-minutes: 180
+  # # This runs the gem5 within SystemC ingration and runs a simple hello-world
+  # # simulation with it.
+  #   systemc-test:
+  #       runs-on: ubuntu-24.04
+  #       container: ghcr.io/gem5/systemc-env:latest
+  #       timeout-minutes: 180
 
-        steps:
-            - uses: actions/checkout@v4
-            - name: Build ARM/gem5.opt
-              run: scons build/ARM/gem5.opt --ignore-style --duplicate-sources -j$(nproc)
-            - name: disable systemc
-              run: scons setconfig build/ARM --ignore-style USE_SYSTEMC=n
-            - name: Build ARM/libgem5_opt.so
-              run: scons build/ARM/libgem5_opt.so --with-cxx-config --without-python --without-tcmalloc -j$(nproc) --duplicate-sources
-            - name: Compile gem5 withing SystemC
-              working-directory: ${{ github.workspace }}/util/systemc/gem5_within_systemc
-              run: make
-            - name: Run gem5 within SystemC test
-              run: ./build/ARM/gem5.opt configs/deprecated/example/se.py -c tests/test-progs/hello/bin/arm/linux/hello
-            - name: Continue gem5 within SystemC test
-              run: LD_LIBRARY_PATH=build/ARM/:/opt/systemc/lib-linux64/ ./util/systemc/gem5_within_systemc/gem5.opt.sc m5out/config.ini
+  #       steps:
+  #           - uses: actions/checkout@v4
+  #           - name: Build ARM/gem5.opt
+  #             run: scons build/ARM/gem5.opt --ignore-style --duplicate-sources -j$(nproc)
+  #           - name: disable systemc
+  #             run: scons setconfig build/ARM --ignore-style USE_SYSTEMC=n
+  #           - name: Build ARM/libgem5_opt.so
+  #             run: scons build/ARM/libgem5_opt.so --with-cxx-config --without-python --without-tcmalloc -j$(nproc) --duplicate-sources
+  #           - name: Compile gem5 withing SystemC
+  #             working-directory: ${{ github.workspace }}/util/systemc/gem5_within_systemc
+  #             run: make
+  #           - name: Run gem5 within SystemC test
+  #             run: ./build/ARM/gem5.opt configs/deprecated/example/se.py -c tests/test-progs/hello/bin/arm/linux/hello
+  #           - name: Continue gem5 within SystemC test
+  #             run: LD_LIBRARY_PATH=build/ARM/:/opt/systemc/lib-linux64/ ./util/systemc/gem5_within_systemc/gem5.opt.sc m5out/config.ini
 
-    dramsys-tests:
-        runs-on: [self-hosted, linux, x64]
-        container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
-        timeout-minutes: 360 # 6 hours
-        steps:
-            - uses: actions/checkout@v4
-            - name: Checkout DRAMSys
-              working-directory: ${{ github.workspace }}/ext/dramsys
-              run: git clone https://github.com/tukl-msd/DRAMSys --branch v5.3.1 --depth 1 DRAMSys
+  #   dramsys-tests:
+  #       runs-on: ubuntu-24.04
+  #       container: ghcr.io/gem5/ubuntu-24.04_all-dependencies:latest
+  #       timeout-minutes: 360 # 6 hours
+  #       steps:
+  #           - uses: actions/checkout@v4
+  #           - name: Checkout DRAMSys
+  #             working-directory: ${{ github.workspace }}/ext/dramsys
+  #             run: git clone https://github.com/tukl-msd/DRAMSys --branch v5.3.1 --depth 1 DRAMSys
 
-              # gem5 is built separately because it depends on the DRAMSys library
-            - name: Build gem5
-              working-directory: ${{ github.workspace }}
-              run: scons build/ALL/gem5.opt -j $(nproc)
+  #             # gem5 is built separately because it depends on the DRAMSys library
+  #           - name: Build gem5
+  #             working-directory: ${{ github.workspace }}
+  #             run: scons build/ALL/gem5.opt -j $(nproc)
 
-            - name: Run DRAMSys Checks
-              working-directory: ${{ github.workspace }}
-              run: |
-                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/arm-hello-dramsys.py
-                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
-                  ./build/ALL/gem5.opt configs/example/dramsys.py
+  #           - name: Run DRAMSys Checks
+  #             working-directory: ${{ github.workspace }}
+  #             run: |
+  #                 ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/arm-hello-dramsys.py
+  #                 ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
+  #                 ./build/ALL/gem5.opt configs/example/dramsys.py
