misc: comment out part of workflow to cache gem5

diff --git a/.github/workflows/sphinx-to-website.yaml b/.github/workflows/sphinx-to-website.yaml
--- a/.github/workflows/sphinx-to-website.yaml
+++ b/.github/workflows/sphinx-to-website.yaml
@@ -26,47 +26,47 @@ jobs:
               if: steps.cache-gem5.outputs.cache-hit != 'true'
               run: scons build/ALL/gem5.opt -j $(nproc)
 
-            - name: Generate RST
-              run: |
-                  apt-get install python3-sphinx
-                  cd docs
-                  ../build/ALL/gem5.opt gem5-sphinx-apidoc -o . ../src/python/gem5 -F -e
+            # - name: Generate RST
+            #   run: |
+            #       apt-get install python3-sphinx
+            #       cd docs
+            #       ../build/ALL/gem5.opt gem5-sphinx-apidoc -o . ../src/python/gem5 -F -e
 
-            - name: Generate Sphinx docs
-              uses: ammaraskar/sphinx-action@master
-              with:
-                  build-command: |
-                      SPHINXBUILD="../build/ALL/gem5.opt gem5-sphinx" make html
-                  docs-folder: docs/
-              # run: |
-              #     python3 -m venv build/
-              #     source build/bin/activate
-              #     pip install sphinx
-              #     scons build/ALL/gem5.opt
-              #     cd docs
-              #     ../build/ALL/gem5.opt gem5-sphinx-apidoc -o . ../src/python/gem5 -F -e
-              #     SPHINXBUILD="../build/ALL/gem5.opt gem5-sphinx" make html
+            # - name: Generate Sphinx docs
+            #   uses: ammaraskar/sphinx-action@master
+            #   with:
+            #       build-command: |
+            #           SPHINXBUILD="../build/ALL/gem5.opt gem5-sphinx" make html
+            #       docs-folder: docs/
+            #   # run: |
+            #   #     python3 -m venv build/
+            #   #     source build/bin/activate
+            #   #     pip install sphinx
+            #   #     scons build/ALL/gem5.opt
+            #   #     cd docs
+            #   #     ../build/ALL/gem5.opt gem5-sphinx-apidoc -o . ../src/python/gem5 -F -e
+            #   #     SPHINXBUILD="../build/ALL/gem5.opt gem5-sphinx" make html
 
-            - name: Add frontmatter
-              run: |
-                  cd docs
-                  python3 add-frontmatter.py
+            # - name: Add frontmatter
+            #   run: |
+            #       cd docs
+            #       python3 add-frontmatter.py
 
-            - name: Commit documentation changes to gem5/website repo
-              # git clone https://github.com/gem5/website.git --branch stable --single-branch stable
-              run: |
-                  git clone https://github.com/erin-le/gem5-website.git website --branch stable --single-branch stable
-                  cp -r docs/_build/html/* website/_pages/documentation/general_docs/sphinx_docs
-                  cd website
-                  git config --local user.email "action@github.com"
-                  git config --local user.name "GitHub Action"
-                  git add .
-                  git commit -m "Update documentation" -a || true
-                  # The above command will fail if no changes were present, so we ignore
-                  # the return code.
-            - name: Push changes
-              uses: ad-m/github-push-action@master
-              with:
-                  branch: stable
-                  directory: website
-                  github_token: ${{ secrets.GITHUB_TOKEN }}
+            # - name: Commit documentation changes to gem5/website repo
+            #   # git clone https://github.com/gem5/website.git --branch stable --single-branch stable
+            #   run: |
+            #       git clone https://github.com/erin-le/gem5-website.git website --branch stable --single-branch stable
+            #       cp -r docs/_build/html/* website/_pages/documentation/general_docs/sphinx_docs
+            #       cd website
+            #       git config --local user.email "action@github.com"
+            #       git config --local user.name "GitHub Action"
+            #       git add .
+            #       git commit -m "Update documentation" -a || true
+            #       # The above command will fail if no changes were present, so we ignore
+            #       # the return code.
+            # - name: Push changes
+            #   uses: ad-m/github-push-action@master
+            #   with:
+            #       branch: stable
+            #       directory: website
+            #       github_token: ${{ secrets.GITHUB_TOKEN }}
